"""make event cover_image_url nullable

Revision ID: 3ac12aa59260
Revises: 67810740e7f4
Create Date: 2026-09-23 20:19:30.125793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac12aa59260'
down_revision: Union[str, Sequence[str], None] = '67810740e7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'cover_image_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'cover_image_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
