"""drop journey and timeline

Revision ID: 5be2eef248e7
Revises: 3ac12aa59260
Create Date: 2026-09-23 20:59:01.486714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5be2eef248e7'
down_revision: Union[str, Sequence[str], None] = '3ac12aa59260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_journey_people_id', table_name='journey_people')
    op.drop_index('ix_journey_people_year', table_name='journey_people')
    op.drop_table('journey_people')
    op.drop_index('ix_timeline_events_id', table_name='timeline_events')
    op.drop_table('timeline_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='timeline_events_pkey')
    )
    op.create_index('ix_timeline_events_id', 'timeline_events', ['id'], unique=False)
    op.create_table('journey_people',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('photo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='journey_people_pkey')
    )
    op.create_index('ix_journey_people_year', 'journey_people', ['year'], unique=False)
    op.create_index('ix_journey_people_id', 'journey_people', ['id'], unique=False)
    # ### end Alembic commands ###
