"""drop award rank field

Revision ID: 9da16d5bf7fa
Revises: ec0e3bc9a65a
Create Date: 2026-09-24 19:13:31.921071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da16d5bf7fa'
down_revision: Union[str, Sequence[str], None] = 'ec0e3bc9a65a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('awards', 'rank')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', sa.Column('rank', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
