"""add awards

Revision ID: b79795bc8d82
Revises: 261ef055aedf
Create Date: 2026-09-23 15:01:37.872294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b79795bc8d82'
down_revision: Union[str, Sequence[str], None] = '261ef055aedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_awards_id'), 'awards', ['id'], unique=False)
    op.create_index(op.f('ix_awards_order_index'), 'awards', ['order_index'], unique=False)
    op.create_index(op.f('ix_awards_year'), 'awards', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_awards_year'), table_name='awards')
    op.drop_index(op.f('ix_awards_order_index'), table_name='awards')
    op.drop_index(op.f('ix_awards_id'), table_name='awards')
    op.drop_table('awards')
    # ### end Alembic commands ###
