"""award rank location date fields

Revision ID: ec0e3bc9a65a
Revises: 5be2eef248e7
Create Date: 2026-09-24 18:50:06.433245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec0e3bc9a65a'
down_revision: Union[str, Sequence[str], None] = '5be2eef248e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', sa.Column('rank', sa.String(length=100), nullable=True))
    op.add_column('awards', sa.Column('location', sa.String(length=150), nullable=True))
    op.add_column('awards', sa.Column('date', sa.Date(), nullable=True))
    op.drop_index('ix_awards_year', table_name='awards')
    op.create_index(op.f('ix_awards_date'), 'awards', ['date'], unique=False)
    op.drop_column('awards', 'year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_awards_date'), table_name='awards')
    op.create_index('ix_awards_year', 'awards', ['year'], unique=False)
    op.drop_column('awards', 'date')
    op.drop_column('awards', 'location')
    op.drop_column('awards', 'rank')
    # ### end Alembic commands ###
